#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Tue Apr 21 18:07:21 UTC 2026
alwaysLogTamperWarnings=true
